<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>annotations</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>ONLINE_JUDGE;ATCODER</DefineConstants>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Speed</OptimizationPreference>
    <IlcInstructionSet>native</IlcInstructionSet>
    <IlcMaxVectorTBitWidth>512</IlcMaxVectorTBitWidth>
    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
    <InvariantGlobalization>true</InvariantGlobalization>
    <WarningsAsErrors>IL2104;IL3053</WarningsAsErrors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode>true</RestoreLockedMode>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ac-library-csharp" Version="3.9.2" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
  </ItemGroup>
</Project>
